# Generated by Django 3.1b1 on 2020-06-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Echipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=250)),
                ('antrenor', models.CharField(max_length=250)),
                ('victorii', models.IntegerField()),
                ('egaluri', models.IntegerField()),
                ('infrangeri', models.IntegerField()),
                ('goluri_primite', models.IntegerField()),
                ('goluri_inscrise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jucator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=250)),
                ('valoare', models.IntegerField()),
                ('echipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campionat.echipa')),
            ],
        ),
    ]
