# Generated by Django 3.1b1 on 2020-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campionat', '0004_auto_20200627_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='meci',
            name='jucat',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
