# Generated by Django 3.1b1 on 2020-06-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campionat', '0005_meci_jucat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meci',
            name='tip',
        ),
    ]
