# Generated by Django 3.1b1 on 2020-06-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campionat', '0006_remove_meci_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasament',
            name='punctaj',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
