# Generated by Django 3.1b1 on 2020-06-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campionat', '0007_clasament_punctaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='meci',
            name='tip_meci',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
