# Generated by Django 3.1b1 on 2020-07-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campionat', '0009_auto_20200708_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasament',
            name='loc_anterior',
        ),
        migrations.RemoveField(
            model_name='clasament',
            name='ultimele_rezultate',
        ),
    ]
