# Generated by Django 3.1b1 on 2020-07-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campionat', '0010_auto_20200709_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='echipa',
            name='valoare',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
